name = "verification"
version = "0.1.0"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "406ebb8c8e2f7e852a1b47764b42494022ce652c"

[[require]]
name = "LeanSearchClient"
git = "https://github.com/leanprover-community/LeanSearchClient"
rev = "c5d5b8fe6e5158def25cd28eb94e4141ad97c843"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "7a62bd13860cd39ac98da16ffc8c24d601353f69"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "b5b9e2bb45ce91e4bc44eaa738c3a8910404ab82"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "954dbc9873f3b4534dc9896604593406d0383520"

[[require]]
name = "importGraph"
git = "https://github.com/leanprover-community/import-graph"
rev = "41f407a8e85b0fdc00910633a8f14754139b63f4"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "360da6fa66c1273b76b6b2d8c5666fd5ac2e3b56"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "f3f26cc72646205ca167117487c008ee1dafe816"

[[require]]
name = "proofwidgets"
git = "https://github.com/leanprover-community/ProofWidgets4"
rev = "e6518a674e62de322b8f79eebeda7bcae2a36bc3"
